# COMP801 - ASSIGNMENT #3 DATA ANALYSIS
## Student Performance Factors

### Independent Variables (Numerical and Categorical)
- Hours_Studied	- Number of hours spent studying per week.
- Attendance - Percentage of classes attended.
- Parental_Involvement - Level of parental involvement in the student's education (Low, Medium, High).
- Access_to_Resources - Availability of educational resources (Low, Medium, High).
- Extracurricular_Activities - Participation in extracurricular activities (Yes, No).
- Sleep_Hours - Average number of hours of sleep per night.
- Previous_Scores - Scores from previous exams.
- Motivation_Level - Student's level of motivation (Low, Medium, High).
- Internet_Access - Availability of internet access (Yes, No).
- Tutoring_Sessions - Number of tutoring sessions attended per month.
- Family_Income - Family income level (Low, Medium, High).
- Teacher_Quality - Quality of the teachers (Low, Medium, High).
- School_Type - Type of school attended (Public, Private).
- Peer_Influence - Influence of peers on academic performance (Positive, Neutral, Negative).
- Physical_Activity - Average number of hours of physical activity per week.
- Learning_Disabilities - Presence of learning disabilities (Yes, No).
- Parental_Education_Level - Highest education level of parents (High School, College, Postgraduate).
- Distance_from_Home - Distance from home to school (Near, Moderate, Far).
- Gender - Gender of the student (Male, Female).
### Dependent Variable
Exam_Score	Final exam score.

### Import packages

In [2]:
import pandas as pd

### Use Pandas to read csv

In [3]:
data = pd.read_csv("C:/Users/admin/OneDrive - Auckland Institute of Studies/AIS files/COMP801 - Research Methods/Assignments/Assignment#3 Data Analysis/Datasets/raw dataset/spf.csv")

In [4]:
data

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

### Describe dataframe to view the Descriptive analysis

In [5]:
data.describe().T

                    count       mean        std   min   25%   50%   75%    max
Hours_Studied      6607.0  19.975329   5.990594   1.0  16.0  20.0  24.0   44.0
Attendance         6607.0  79.977448  11.547475  60.0  70.0  80.0  90.0  100.0
Sleep_Hours        6607.0   7.029060   1.468120   4.0   6.0   7.0   8.0   10.0
Previous_Scores    6607.0  75.070531  14.399784  50.0  63.0  75.0  88.0  100.0
Tutoring_Sessions  6607.0   1.493719   1.230570   0.0   1.0   1.0   2.0    8.0
Physical_Activity  6607.0   2.967610   1.031231   0.0   2.0   3.0   4.0    6.0
Exam_Score         6607.0  67.235659   3.890456  55.0  65.0  67.0  69.0  101.0